# Generated by Django 4.2.1 on 2023-09-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_string", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField(null=True)),
                ("end_date", models.DateTimeField(null=True)),
                ("data", models.BinaryField()),
            ],
            options={
                "unique_together": {("id_string", "start_date", "end_date")},
            },
        ),
        migrations.DeleteModel(
            name="CacheIntermediate",
        ),
        migrations.DeleteModel(
            name="CacheManager",
        ),
    ]
