# Generated by Django 4.2.1 on 2023-08-17 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsoldpriceupload',
            name='source',
            field=models.CharField(default='other', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 9, 8, 29, 134035)),
        ),
    ]
