# Generated by Django 4.2.1 on 2023-09-01 08:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCorrectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='absencegroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='absence',
            name='absence_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.absencetype'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TimeCorrectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('time_start_of_work', models.DateTimeField(null=True)),
                ('time_start_of_lunch_break', models.DateTimeField(null=True)),
                ('time_end_of_lunch_break', models.DateTimeField(null=True)),
                ('time_end_of_work', models.DateTimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_accepted', models.BooleanField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.user')),
                ('time_correction_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.timecorrectiongroup')),
                ('time_correction_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.timecorrectiontype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='absencegroup',
            name='absence_end_date',
        ),
        migrations.RemoveField(
            model_name='absencegroup',
            name='absence_start_date',
        ),
        migrations.RemoveField(
            model_name='absencegroup',
            name='absence_type',
        ),
    ]
