# Generated by Django 3.2 on 2023-04-09 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='microsoft_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='projectusergroup',
            unique_together={('user', 'project_group')},
        ),
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active', models.BooleanField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_project_users', to='backend.user')),
                ('project_user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectusergroup')),
                ('project_user_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectuserrole')),
            ],
        ),
    ]
