# Generated by Django 3.2 on 2023-04-09 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_project_user_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='project_user_role',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='project_user_roles',
            field=models.ManyToManyField(blank=True, to='backend.ProjectUserRole'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
