# Generated by Django 4.2.1 on 2023-08-17 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_partsoldpriceupload_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstaffcostgroup',
            name='work_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockexchangedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 9, 11, 8, 355175)),
        ),
    ]
