# Generated by Django 4.2.1 on 2023-09-25 09:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_databasecache_delete_cacheintermediate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="derivativeconstelliumderivativelmcconnection",
            old_name="derivative_lmc",
            new_name="derivative_lmc_group",
        ),
        migrations.AlterUniqueTogether(
            name="derivativeconstelliumderivativelmcconnection",
            unique_together={("derivative_constellium", "derivative_lmc_group")},
        ),
    ]
