# Generated by Django 4.2.1 on 2023-09-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_databasecache_delete_cacheintermediate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecorrection',
            name='hash_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='timecorrection',
            name='time_correction_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='absence',
            name='absence_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_end_of_lunch_break',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_end_of_work',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_start_of_lunch_break',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_start_of_work',
            field=models.TimeField(null=True),
        ),
    ]
