# Generated by Django 4.2.1 on 2023-10-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_timecorrection_hash_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecorrection',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='hash_code',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='is_accepted',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_end_of_lunch_break',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_end_of_work',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_start_of_lunch_break',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timecorrection',
            name='time_start_of_work',
            field=models.TimeField(default=None, null=True),
        ),
    ]
