# Generated by Django 4.2.1 on 2023-10-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0003_timecorrection_hash_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectNumberGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_number", models.CharField(max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_number",
        ),
        migrations.AddField(
            model_name="project",
            name="currency",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.currency",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="customer_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.customergroup",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="file_group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.filegroup",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="probability_of_nomination",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_status",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.projectstatus",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.projecttype",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ProjectNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("network_number", models.BigIntegerField(null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.user",
                    ),
                ),
                (
                    "project_number_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.projectnumbergroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="project",
            name="project_number_group",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.projectnumbergroup",
            ),
        ),
    ]
