# Generated by Django 4.2.1 on 2023-09-27 14:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0003_rename_derivative_lmc_derivativeconstelliumderivativelmcconnection_derivative_lmc_group_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="derivativelmcvolume",
            name="volume_date",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 27, 14, 56, 7, 548470)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="derivativelmcvolume",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
