# Generated by Django 4.2.1 on 2023-10-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_derivativelmcvolume_volume_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                ("sop", models.DateField()),
                ("eop", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("used_volume", models.BooleanField(default=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.user",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectPhaseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="derivativeconstellium",
            name="estimated_price",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="derivativeconstellium",
            name="estimated_weight",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="derivativeconstellium",
            name="prediction_accuracy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.predictionaccuracy",
            ),
        ),
        migrations.CreateModel(
            name="CustomerVolumeVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "customer_volume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.customervolume",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerVolumeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "derivative_constellium_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.derivativeconstelliumgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="customervolume",
            name="customer_volume_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.customervolumegroup",
            ),
        ),
        migrations.AddField(
            model_name="customervolume",
            name="project_phase_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.projectphasetype",
            ),
        ),
    ]
