# Generated by Django 3.2 on 2023-04-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_transfer_project_number_to_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='creator',
        ),
    ]
