# Generated by Django 4.2.1 on 2023-10-16 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_customervolume_projectphasetype_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customervolumevolume",
            old_name="date",
            new_name="volume_date",
        ),
    ]
