# Generated by Django 3.2 on 2023-04-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_project_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivativeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='projectuser',
            old_name='project_user_roles',
            new_name='project_user_role',
        ),
        migrations.AddField(
            model_name='projectuserrole',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='DerivativeConstelliumGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.projectgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DerivativeConstellium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('sop_date', models.DateField()),
                ('eop_date', models.DateField()),
                ('estimated_price', models.FloatField()),
                ('estimated_weight', models.FloatField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('derivative_constellium_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.derivativeconstelliumgroup')),
                ('derivative_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.derivativetype')),
                ('prediction_accuracy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.predictionaccuracy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=100)),
                ('group_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('data', models.BinaryField()),
            ],
            options={
                'unique_together': {('manager_name', 'group_id', 'date')},
            },
        ),
    ]
