# Generated by Django 3.2 on 2023-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20230413_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='project_user_role',
            field=models.ManyToManyField(to='backend.ProjectUserRole'),
        ),
    ]
