# Generated by Django 3.2 on 2023-04-16 10:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_projectuser_project_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('company_name', models.CharField(max_length=255)),
                ('group_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DerivativeGroupLMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lmc_full_code', models.CharField(max_length=255, unique=True)),
                ('lmc_model_code', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('lmc_full_code', 'lmc_model_code')},
            },
        ),
        migrations.CreateModel(
            name='DerivativeVolumeGroupLMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('derivative_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.derivativegrouplmc')),
            ],
            options={
                'unique_together': {('derivative_group', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='RevisionLMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('revision_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LMCDerivative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('region', models.CharField(max_length=255)),
                ('trade_region', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('local_model_line', models.CharField(max_length=255)),
                ('local_program_code', models.CharField(max_length=255)),
                ('local_production_model', models.CharField(max_length=255)),
                ('global_production_model', models.CharField(max_length=255)),
                ('gvw', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('production_type', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(db_column='type', max_length=255)),
                ('regional_size', models.CharField(max_length=255)),
                ('regional_body_type', models.CharField(max_length=255)),
                ('regional_status', models.CharField(max_length=255)),
                ('global_size', models.CharField(max_length=255)),
                ('global_body_type', models.CharField(max_length=255)),
                ('global_status', models.CharField(max_length=255)),
                ('sop_date', models.DateField()),
                ('eop_date', models.DateField()),
                ('next_facelift', models.DateField()),
                ('last_actual', models.DateField()),
                ('design_lead_location', models.CharField(max_length=255)),
                ('design_lead_country', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('derivative_group_lmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.derivativegrouplmc')),
                ('design_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_leads', to='backend.customer')),
                ('global_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_makes', to='backend.customer')),
                ('local_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_makes', to='backend.customer')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='backend.customer')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.customerplant')),
                ('revision_lmc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.revisionlmc')),
                ('sales_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_groups', to='backend.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DerivativeVolumeLMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('volume', models.PositiveIntegerField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user')),
                ('lmc_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.revisionlmc')),
                ('volume_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.derivativevolumegrouplmc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
