version: '3'
services:
  db:
    container_name: database
    image: mariadb:latest
    networks:
      - internal
    volumes:
      - db_volume:/var/lib/mysql
    env_file: .env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    container_name: cache
    image: redis:latest
    networks:
      - internal
    volumes:
      - cache_volume:/data
    env_file: .env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  http:
    container_name: http
    build: ./http
    networks:
      - internal
      - external
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - internal
      - external
    restart: allways
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_volume:
  cache_volume:

networks:
  internal:
  external:
    external: true