version: '3'
services:
  db:
    container_name: database
    image: mariadb:latest
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=orm_test
      - MARIADB_USER=orm_test
      - MARIADB_PASSWORD=orm_test_secret_key
      - MARIADB_ROOT_PASSWORD=root123
    healthcheck:
      # test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      test: ["CMD", "healthcheck.sh", "--connect", "--user", "orm_test", "--password", "orm_test_secret_key", "--host", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  cache:
    container_name: cache
    image: redis:latest
    volumes:
      - cache_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  http:
    container_name: http
    build: ./http
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_volume:
  cache_volume:
