version: '3'
services:
  db:
    container_name: database
    image: mariadb:latest
    volumes:
      - db_volume:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=orm_test
      - MARIADB_USER=orm_test
      - MARIADB_PASSWORD=ormtestsecretkey
      - MARIADB_ROOT_PASSWORD=root123
    healthcheck:
      test: ["CMD", "mariadb", "-u", "orm_test", "-pormtestsecretkey", "-e", "SHOW DATABASES;"]
      timeout: 3s
      retries: 20
  cache:
    container_name: cache
    image: redis:latest
    volumes:
      - cache_volume:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 20
  daphne:
    container_name: daphne
    build: ./django
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8001"]
      timeout: 3s
      retries: 5
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx-config.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      daphne:
        condition: service_healthy
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
  celery_worker:
    container_name: celery_worker
    build: ./celery
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://cache:6379/0
volumes:
  db_volume:
  cache_volume:
